### ISSUE TITLE
StevesUEExamples doesn't work with current version StevesUEHelpers

### ISSUE THREAD

**Issue by calicoday** [sinbad/StevesUEExamples#1]
Heya. Stumbled on a snag trying to run the StevesUEExamples project (prob wouldn't have noticed if I'd `git clone`d with the right params, instead of using the dumbest poss approach). I downloaded 'Helpers and 'Examples as zips, dragged 'Helpers into the 'Examples Plugins folder and double-clicked the .uproject. Got "do you want to build source?" and I said yes. Compile failed with 9 errors, all undeclared identifier (GetStyle, GetClickMethod, etc) in several files of the StevesUI subdir.

I downloaded the zip of the e2f0f47 commit of 'Helpers (the sub repo ref'd in 'Examples), dragged it into 'Examples and it compiled and came up fine (haven't played with it yet).

**Comment by sinbad** [comment]
Yeah this is expected. You're supposed to clone it with the helpers lib submodule. I wish GH would let me turn off the "download as zip" option because it plain doesn't work for submodules and all my libs & examples use submodules for library source access.

**Comment by calicoday** [comment]
Fair enough, re git clone for getting the right pieces down. But is it intended not to work with the current, newer 'Helpers? Is there something here that makes it unsuitable for newer projs?

**Comment by sinbad** [comment]
I just hadn't loaded this examples project up since UE 5.1 - I mostly use the helpers with other projects like the SUDS examples & my game. A couple of small fixes were needed in the Target.cs files, done now ( https://github.com/sinbad/StevesUEExamples/commit/a5b6f39e83d63585767fd9f2e10b2b51bfb42dc2)
